### ISSUE TITLE
MPOG Stress Test: BitStomach 500 Error

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/precision-feedback-pipeline#166]
In reproduction of the errors from the stress test, have successfully patched 500 errors from pictoralist, however some input_messages fail due to errors from BitStomach instead.

Diagnosed with **Provider_44** using LDT
Verified against local, heroku, and GCP instances

See console log below:

```zsh
INFO|  Calling BitStomach from main...
INFO:     127.0.0.1:52467 - "POST /createprecisionfeedback/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...
...
  File ".../precision-feedback-pipeline/main.py", line 159, in createprecisionfeedback
    BS=bs.annotate()
       ^^^^^^^^^^^^^
  File ".../precision-feedback-pipeline/bit_stomach/bit_stomach.py", line 167, in annotate
    a=pr.goal_trend_annotate(measure_name,**self.goal1_dicts)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../precision-feedback-pipeline/bit_stomach/prepare_data_annotate.py", line 116, in goal_trend_annotate
    a = trend_annotate(self.a,self.s13,measure_data2,comparator_bnode)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../precision-feedback-pipeline/bit_stomach/trend_annotate.py", line 35, in trend_annotate
    number=find_number(back_up_df,trend_sign1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../precision-feedback-pipeline/bit_stomach/trend_annotate.py", line 126, in find_number
    if lista[z]<=lista[y]:
       ~~~~~^^^
IndexError: list index out of range
```

**Comment by icejag** [comment]
To Test this error-
Try the test case-[1, "NMB01", "2022-01-01", 2, 0, 2, 84.7, 100.0, 100.0, 90.0],
[1, "NMB01", "2022-03-01", 11, 6, 17, 84.8, 100.0, 100.0, 90.0],
[1, "NMB01", "2022-04-01", 22, 13, 35, 84.6, 100.0, 100.0, 90.0],
[1, "NMB01", "2022-05-01", 8, 12, 20, 84.9, 100.0, 100.0, 90.0]
